// ----- Carro ---- 
### Adicionar - Serviço ###
POST http://localhost:2000/api/carros
Content-Type: application/json

{
	"marca": "Porsche",
	"modelo": "911",
	"kms": "20000",
	"combustivel": "Gasolina",
	"ano": "2021",
	"caixa": "Automatica",
	"img": "https://cdn.ferrari.com/cms/network/media/img/resize/5db9875fb6fd1830814db7f1-ferrari-458-italia-architecture15_scont?",
	"garantia": "dois anos",
	"preco" : "180980",
	"cor" : "Black"
}

### Listagem - TUDO ###
GET http://localhost:2000/api/carros

### Listagem - By ID ###
GET http://localhost:2000/api/carros/664cca17e2a8601605cf4ce4

### Apagar - By ID ###
DELETE http://localhost:2000/api/carros/6641fe020068a22e6401c124

### Atualizar - By ID ###
PUT http://localhost:2000/api/carros/664b236ebc63c671b7715998
Content-Type: application/json

{
	"marca": "Volvo",
	"modelo": "784",
	"kms": "20000",
	"combustivel": "Gasolina",
	"ano": "2022",
	"caixa": "Automatica",
	"img": "https://cdn.ferrari.com/cms/network/media/img/resize/5db9875fb6fd1830814db7f1-ferrari-458-italia-architecture15_scont?",
	"garantia": "dois anos",
	"preco" : "180980",
	"cor" : "Black"
}