// ----- Serviços ---- 
### Adicionar - Serviço ###
POST http://localhost:2000/api/users
Content-Type: application/json

{
	"userid" : "admin",
    "password" : "admin"
}

### Listagem - TUDO ###
GET http://localhost:2000/api/users

### Listagem - By ID ###
GET http://localhost:2000/api/users/6641fe020068a22e6401c124

### Apagar - By ID ###
DELETE http://localhost:2000/api/users/6641fe020068a22e6401c124

### Atualizar - By ID ###
PUT http://localhost:2000/api/users/6641fbe4da5e40e39c358c48
Content-Type: application/json

{
	"userid" : "admin",
    "password" : "admin"
}